### PR TITLE
Stunswords!

### PR DESCRIPTION
**Pull request by cebutris**
Adds stunswords! They're modified stunbatons, that look like swords! Big thanks to everyone who helped me with making the conversion kit.

Each SecVend comes with two kits, one that can be obtained with a coin, and one that can be obtained by hacking the vendor

- [x] item sprites
- [x] item code
- [x] conversion kit
- [x] add kit to vendor
- [ ] inhand sprites
- [ ] slight modifications
- [ ] more sprites?

I'm planning on making the stunswords slightly different than regular batons. They'll probably be a bit bigger but also be able to fit on your back or something. I dunno.

### CODE REVIEW

**Comment by fludd12** [comment]
:zap: :crossed_swords: :zap:

**Comment by cebutris** [comment]
UPDATE: Working on these again. Inhand sprites are done, just need to figure out how to actually assign them to the items. Expect this to take way longer than it needs to, due to the fact that it is me doing it.

**Comment by AnonymousHybi** [comment]
icons/mob/items/
this contains the .dmis on which the items use for it's right and left handed sprite.
I'm not so sure which item you want on it, so i assume stunsword, it will go into lefthand_melee.dmi and righthand_melee.dmi

**Comment by cebutris** [comment]
The issue is, I'd rather make new files for all of the content added by ARFS, rather than use existing files.

**Comment by cebutris** [comment]
Due to 🍝 code I'll just do what everyone else did. Don't blame me.

**Comment by cebutris** [comment]
Closing because merge conflicts. I'll make a new PR later.

**Pull request closed without merging**
